<?xml version='1.0'?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version='1.0'>
  <xsl:include href="../dblatex-config.xsl"/>

  <xsl:param name="local.l10n.xml" select="document('')"/>
  <l:i18n xmlns:l="http://docbook.sourceforge.net/xmlns/l10n/1.0">
    <l:l10n language="en">
      <l:context name="xref-number">
        <l:template name="chapter" text="chapter %n"/>
        <l:template name="figure" text="figure %n"/>
        <l:template name="section" text="section %n"/>
      </l:context>
      <l:context name="xref">
        <l:template name="page" text="on page %p"/>
      </l:context>
    </l:l10n>
  </l:i18n>

  <!-- Override the built-in template to basically completely customize the preamble -->
  <xsl:template match="book|article" mode="preamble-disabled">
    <xsl:param name="lang"/>
    <xsl:variable name="info" select="bookinfo|articleinfo|artheader|info"/>

    <xsl:text>% -----------------------------------------  &#10;</xsl:text>
    <xsl:text>% Autogenerated LaTeX file from XML DocBook  &#10;</xsl:text>
    <xsl:text>% -----------------------------------------  &#10;</xsl:text>
    <!-- Parameters to pass to python parser -->
    <xsl:call-template name="py.params.set"/>
    <xsl:text>\documentclass</xsl:text>
    <xsl:if test="$latex.class.options!=''">
      <xsl:value-of select="concat('[',$latex.class.options,']')"/>
    </xsl:if>
    <xsl:text>{</xsl:text>
    <xsl:choose>
      <xsl:when test="self::book">
        <xsl:value-of select="$latex.class.book"/>
      </xsl:when>
      <xsl:otherwise>
        <xsl:value-of select="$latex.class.article"/>
      </xsl:otherwise>
    </xsl:choose>
    <xsl:text>}&#10;</xsl:text>

    <xsl:variable name="external.docs">
      <xsl:call-template name="make.external.docs"/>
    </xsl:variable>
    
    <xsl:call-template name="encode.before.style">
      <xsl:with-param name="lang" select="$lang"/>
    </xsl:call-template>
    <xsl:text>\usepackage{fancybox}&#10;</xsl:text>
    <xsl:text>\usepackage{makeidx}&#10;</xsl:text>

    <xsl:call-template name="user.params.set"/>
    <!-- Load babel before the style (bug #babel/3875) -->
    <xsl:call-template name="babel.setup"/>

    <!-- Load xr before hyperref -->
    <xsl:if test="$external.docs != ''">
      <xsl:text>\usepackage{xr-hyper}&#10;</xsl:text>
    </xsl:if>

    <!-- Paper and Page setup -->
    <xsl:call-template name="page.setup"/>

    <xsl:text>\usepackage[hyperlink]{</xsl:text>
    <xsl:value-of select="$latex.style"/>
    <xsl:text>}&#10;</xsl:text>

    <xsl:call-template name="encode.after.style">
      <xsl:with-param name="lang" select="$lang"/>
    </xsl:call-template>
    <xsl:call-template name="lang.setup"/>
    <xsl:call-template name="image.setup"/>
    <xsl:call-template name="citation.setup"/>
    <xsl:call-template name="biblio.setup"/>
    <xsl:call-template name="footnote.setup"/>
    <xsl:call-template name="annotation.setup"/>
    <xsl:call-template name="user.params.set2"/>
    <xsl:call-template name="inline.setup"/>
    <xsl:apply-templates select="." mode="docinfo"/>

    <!-- Document title -->
    <xsl:variable name="title">
      <xsl:apply-templates select="(title
                                   |info/title
                                   |bookinfo/title
                                   |articleinfo/title
                                   |artheader/title)[1]" mode="coverpage"/>
    </xsl:variable>

    <!-- Get the Authors -->
    <xsl:variable name="authors">
      <xsl:if test="$info">
        <xsl:choose>
          <xsl:when test="$info/authorgroup/author">
            <xsl:apply-templates select="$info/authorgroup"/>
          </xsl:when>
          <xsl:when test="$info/author">
            <xsl:call-template name="person.name.list">
              <xsl:with-param name="person.list" select="$info/author"/>
            </xsl:call-template>
          </xsl:when>
        </xsl:choose>
      </xsl:if>
    </xsl:variable>

    <xsl:text>\title{</xsl:text>
    <xsl:value-of select="$title"/>
    <xsl:text>}&#10;</xsl:text>
    <xsl:text>\author{</xsl:text>
    <xsl:value-of select="$authors"/>
    <xsl:text>}&#10;</xsl:text>

    <!-- Fill the PDF metadata -->
    <xsl:call-template name="pdf-document-information">
      <xsl:with-param name="pdfauthor" select="$authors"/>
    </xsl:call-template>

    <!-- The external documents -->
    <xsl:if test="$external.docs != ''">
      <xsl:value-of select="$external.docs"/>
    </xsl:if>

    <!-- Set the collaborator table -->
    <xsl:call-template name="collab.setup">
      <xsl:with-param name="authors" select="$authors"/>
    </xsl:call-template>

    <xsl:text>\makeindex&#10;</xsl:text>
    <xsl:text>\makeglossary&#10;</xsl:text>

    <!-- Apply the revision history here -->
    <xsl:apply-templates select="$info/revhistory"/>

    <xsl:call-template name="verbatim.setup"/>
  </xsl:template>

  <!-- Override the built-in template to add a short table of contents -->
  <xsl:template match="book|article" mode="toc_lots">
    <xsl:if test="$doc.toc.show != '0'">
      <xsl:text>\shorttoc{Short table of contents}{1}&#10;</xsl:text>
      <xsl:text>\renewcommand\contentsname{Detailed table of contents}&#10;</xsl:text>
      <xsl:text>\setcounter{tocdepth}{3}&#10;</xsl:text>
      <xsl:text>\tableofcontents&#10;</xsl:text>
    </xsl:if>
    <xsl:apply-templates select="." mode="lots"/>
  </xsl:template>

  <!-- Target Database set by the command line

  <xsl:param name="target.database.document">olinkdb.xml</xsl:param>
  -->

  <!-- Use the Bob Stayton's Tip related to olinking -->
  <!--xsl:param name="current.docid" select="/*/@id"/-->

  <!-- Use the literal scaling feature -->
  <!--xsl:param name="literal.extensions">scale.by.width</xsl:param-->

  <!-- We want the TOC links in the titles, and in blue. -->
  <!--xsl:param name="latex.hyperparam">colorlinks,linkcolor=blue,pdfstartview=FitH</xsl:param-->

  <!-- Put the dblatex logo -->
  <!--xsl:param name="doc.publisher.show">1</xsl:param-->

  <!-- Show the list of examples too -->
  <!--xsl:param name="doc.lot.show">figure,table,example</xsl:param-->

  <!-- DocBook like description -->
  <!--xsl:param name="term.breakline">1</xsl:param-->

  <!-- Manpage titles not numbered -->
  <!--xsl:param name="refentry.numbered">0</xsl:param-->
</xsl:stylesheet>
